# Generated by Django 2.2.14 on 2020-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_requesttool'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttool',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
