# Generated by Django 2.2.14 on 2020-12-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_requesttool_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttool',
            name='user',
        ),
        migrations.AddField(
            model_name='requesttool',
            name='from_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='u_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesttool',
            name='to_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='u_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
