# Generated by Django 2.2.14 on 2020-12-02 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20201201_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttool',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesttool',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReplayTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('from_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_u', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RequestTool')),
                ('to_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
