# Generated by Django 2.2.14 on 2020-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='period',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
