# Generated by Django 3.0.8 on 2020-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
                ('area_coverage', models.CharField(max_length=100)),
                ('rate_range', models.CharField(max_length=100)),
            ],
        ),
    ]
