# Generated by Django 3.0.8 on 2020-11-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201126_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('tool_name', models.CharField(max_length=50, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='AreaCoverage',
        ),
        migrations.DeleteModel(
            name='PriceRange',
        ),
        migrations.DeleteModel(
            name='RateRange',
        ),
    ]
