# Generated by Django 3.0.8 on 2020-11-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201126_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filters',
        ),
    ]
